### ISSUE TITLE
Invalid query parameter $search

### ISSUE THREAD

**Issue by soullivaneuh** [rayfoss/feathers-nedb-fuzzy-search#4]
With this service hook configuration:

```typescript
before: {
  all: [authenticate('jwt')],
  find: [
    (context: HookContext) => {
      const { params } = context;

      if (params.provider && !params.user.isAdmin) {
        Object.assign(params.query, {
          driverId: params.user._id,
        });
      }
    },
    search({
      fields: ['customer'],
    }),
  ],
```

And this client query:

```javascript
{
  query: {
    customer: {
      $search: search,
    },
  }
}
```

I have the following error:

```
Invalid query parameter $search
```

Not sure what I'm missing here. The `customer` field is a text field.

**Comment by soulofmischief** [comment]
@soullivaneuh you may need to whitelist the `$search` parameter as per new feathers adapter specs. Check here: https://github.com/rayfoss/feathers-nedb-fuzzy-search/pull/5/commits/13955995958a74fb86fa51eb72c1b38aab44b2f0

**Comment by vladdancer** [comment]
Hey @soullivaneuh you need to add $search op to the service options:

```js
const options = {
    Model: createModel(app),
    paginate: app.get('paginate'),
    //multi: true,
    whitelist: [ '$where', '$search' ] // <— add this.
  };

  // Initialize our service with any options it requires
  app.use('/your-service', new YourServiceModel(options, app));
```
The documentation is missing code example where to add it, so I've attached the above.

Also I think then the right query will be:
```
{
  query: {
      $search: "Jane"
  }
}
```
or url equivalent will be: `/members?$search=Jane`

BTW: I'm using fields shorthand definition in hook: `{before: {find: [ search(['fullName']) ]}}`

**Comment by soullivaneuh** [comment]
Works like a charm, thanks for the help and the shorthand tips!

I would suggest you to add an example like this on the documentation to express this needs. I just didn't saw the notice. :-)
