### ISSUE TITLE
Bump release tag to match v1.4.0, publish new npm version

### ISSUE THREAD

**Issue by soulofmischief** [rayfoss/feathers-nedb-fuzzy-search#8]
Thank ye kindly :)

**Comment by FossPrime** [comment]
![347000-120806_th_silverblues](https://user-images.githubusercontent.com/876076/89846258-55afce00-db46-11ea-82ed-cab35f54cc3a.jpg)

**Comment by FossPrime** [comment]
Woohoo, looks like I should be able to do this today. Thankfully NPM support is alive and well

**Comment by FossPrime** [comment]
6 support rounds and 8 2fa codes later... all set!

**Comment by soulofmischief** [comment]
Thanks a ton! Sorry about your npm woes :(
